audit_header: false
title: Bay Area Real Estate Video Blog with Brett Jennings
description: >-
  Our mission at Brett Jennings Real Estate Experts is to be your best resource
  for the Bay Area real estate advice. Whether you are a buyer, seller, or
  investor, our team of professionals can answer any questions you might have
  about real estate. If you are looking to buy or sell a home, you can get all
  the information and the latest updates, tips, and tricks from The Brett
  Jennings Real Estate Experts, your professional Bay Area Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /testimonials/
  - title: 5 Star Vendors
    url: /vendors/
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: About
    url: https://www.therealexperts.com/members/brett-jennings/
  - title: Our Team
    url: https://www.therealexperts.com/our-team/
client:
  name: Brett Jennings
  title:
  license_number:
  about_markdown: >
    Brett Jennings is the owner and founder of Brett Jennings Real Estate
    Experts. Brett is an award-winning luxury home marketing specialist and also
    holds a certificate in negotiation from Harvard Law. In 2017, the Wall
    Street Journal recognized Brett and his team as one of the top 250 real
    estate groups in the United States. With over one million agents in the
    country, this prestigious award places Brett in the top 1/10th of the top 1%
    among his peers.


    Although these statistics are impressive, Brett’s true passion is helping
    people make smart real estate decisions that positively transform their
    lives. His extensive background in real estate, finance, and life coaching
    enables him to draw from a deep well of life experience as he helps his
    clients make informed, intelligent decisions. In a fluctuating real estate
    landscape, the expertise and attention he provides are necessary and rare.


    Described by his peers and clients as energetic, focused, determined, and
    engaged, Brett always goes above and beyond. He provides his buyers access
    to his curated list of over 250 off-market properties, and his sellers
    benefit from his market-proven home selling process that has set
    record-breaking prices in almost every neighborhood he sells in. His
    best-selling book, The New Rise in Real Estate, serves as a further resource
    for clients wanting to make the most of the current market.
  market: Bay Area
  brand: Brett Jennings Real Estate Experts
  brokerage:
  address: 910 E Hamilton Ave, Suite 130 , Campbell Ca 95008
  phone: 408-596-4490
  phone_type:
  phone2:
  phone2_type:
  email: Brett@TheRealExperts.com
  url: http://www.TheRealExperts.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://get.homebot.ai/?id=bfb88f6d-2f28-4650-8fdc-c96a6ee7c8fc
  second_CTA_text: Home Search
  second_CTA_URL: >-
    https://realestateexperts.ruuster.com/agent/brett-jennings/listings?address=%7B%22value%22%3A%22ChIJ9T_5iuTKj4ARe3GfygqMnbk%22%2C%22label%22%3A%22San%20Jose%2C%20CA%22%2C%22data%22%3A%5B%7B%22offset%22%3A0%2C%22value%22%3A%22San%20Jose%22%7D%2C%7B%22offset%22%3A10%2C%22value%22%3A%22CA%22%7D%5D%2C%22source%22%3A%22googleAutocomplete%22%7D&bathrooms=all&bedrooms=all&priceMax=0&priceMin=0&status=Active&status=ComingSoon&type=all
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Bay Area Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://get.homebot.ai/?id=bfb88f6d-2f28-4650-8fdc-c96a6ee7c8fc
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a Home?
    CTA_text2: Search the entire MLS for your Bay Area home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://www.bayareahomesearch.com/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/RealEstateExpertsSV/
  linkedin_url: https://www.linkedin.com/in/brettjennings/
  gplus_url:
  youtube_url: https://www.youtube.com/user/TheBrettJenningsTeam?feature=watch
  twitter_url: https://twitter.com/thejenningsteam
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/BrettJenningsTeam/
  trulia_url: >-
    http://www.trulia.com/profile/brett-jennings-team-broker-95125-13475463/reviews
  yelp_url: http://www.yelp.com/biz/brett-jennings-real-estate-experts-los-gatos
  podcast_url:
podcast:
  title: Bay Area Real Estate Podcast with Brett Jennings
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Silicon
    Valley Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Brett Jennings Real Estate Experts -
    your professional Silicon Valley Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Silicon Valley,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Brett Jennings
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/real-experts-header.webp
  logo_width_number: 80
  hero_text: Bay Area Real Estate Journal
  hero_background_hex: '#11365d'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#11365d'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#464f61'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
